### ISSUE TITLE
API requests yield empty responses

### ISSUE THREAD

**Issue by kylbar** [bundesAPI/hochwasserzentralen-api#6]
Currently, all requests to the different endpoints give empty responses. The status code always shows 200 though. 

Is this behaviour due to missing warning alerts or is there some other issue on the server side?

![grafik](https://github.com/bundesAPI/hochwasserzentralen-api/assets/22305662/4f50d79b-2e3b-45e9-b2c4-c3ea7b1c4861)

**Comment by joshis9** [comment]
same issue here

**Comment by wallo66** [comment]
also same issue here

**Comment by it-boerner** [comment]
Ich glaube die API sind nicht mehr öffentlich

**Comment by stephan192** [comment]
I've asked LHP via Email why it is not working anymore.

Response:
They locked the API for external access. They say i was using an API which was not offical released to public and is now only internally available for feeding the LHP homepage with data.

**Comment by kylbar** [comment]
> I've asked LHP via Email why it is not working anymore.
> 
> Response: They locked the API for external access. They say i was using an API which was not offical released to public and is now only internally available for feeding the LHP homepage with data.

That's too bad. Thanks for the information though!

**Comment by t-huyeng** [comment]
Hello, you are using the wrong URL. 
https://hochwasserzentralen.api.proxy.bund.dev is as visible in the URL a proxy which is provided by BundDEV to be able to use the data via the OpenAPI interface here: https://hochwasserzentralen.api.bund.dev/. 

This is because CORS are not fully supported by the portal itself. 
Can you please check your request with the correct URL?

**Comment by mileippert** [comment]
Looks like there is an additional parameter `ki` required. The following command responds with data for one of my local rivers. 

`curl 'https://www.hochwasserzentralen.de/webservices/get_infospegel.php' --data-raw 'pgnr=BW_92&ki=814949302301'`

The value for this field can be found in `aktuelle_situation` within a script block. Currently this is passed to a function named `addLagePegelInteractive(<ki value here>)`. It is sad that this information is not available through public API anymore.
